export type Fuel = "Petrol" | "Diesel" | "Hybrid";
export type Transmission = "Automatic" | "Manual";
export type Body = "Hatchback" | "Sedan" | "SUV" | "Pickup" | "Wagon" | "Crossover";
export type Origin = "Import" | "Local";
export type Condition = "Excellent" | "Very good" | "Good";
export type SellerKind = "Yard" | "Dealer" | "Private";
export type PartCondition = "New" | "Used" | "Refurbished";

export interface Car {
  id: string;
  title: string;
  make: string;
  model: string;
  trim: string;
  year: number;
  price: number;
  marketValue: number;
  mileage: number;
  fuel: Fuel;
  transmission: Transmission;
  body: Body;
  color: string;
  city: string;
  location: string;
  origin: Origin;
  auctionGrade?: string;
  dutyPaid: boolean;
  owners: number;
  engine: string;
  features: string[];
  description: string;
  image: string;
  gallery: string[];
  sellerId: string;
  daysListed: number;
  views: number;
  condition: Condition;
  featured?: boolean;
  demand: number;
}

export interface Part {
  id: string;
  title: string;
  brand: string;
  category: string;
  price: number;
  condition: PartCondition;
  fitment: string[];
  city: string;
  location: string;
  image: string;
  crop: "img-cover" | "img-wheel" | "img-lamp" | "img-front" | "img-low";
  description: string;
  sellerId: string;
  stock: number;
  oem?: string;
}

export interface Yard {
  id: string;
  name: string;
  city: string;
  location: string;
  kind: SellerKind;
  established: number;
  bio: string;
  listings: number;
  rating: number;
  speciality: string;
}

export interface Thread {
  id: string;
  title: string;
  author: string;
  excerpt: string;
  replies: number;
  likes: number;
  time: string;
  pinned?: boolean;
}

export interface Nation {
  slug: string;
  name: string;
  tagline: string;
  make: string;
  members: number;
  cover: string;
  about: string;
  rules: string[];
  threads: Thread[];
}

export const CITIES = [
  "Nairobi",
  "Mombasa",
  "Kisumu",
  "Nakuru",
  "Eldoret",
  "Thika",
] as const;

export const MAKES = [
  "Toyota",
  "Subaru",
  "Mazda",
  "Honda",
  "Nissan",
  "BMW",
  "Mercedes-Benz",
  "Land Rover",
  "Isuzu",
  "Volkswagen",
] as const;

export const BODIES: Body[] = [
  "Hatchback",
  "Sedan",
  "SUV",
  "Pickup",
  "Wagon",
  "Crossover",
];

export const PART_CATEGORIES = [
  "Tyres & wheels",
  "Brakes",
  "Engine",
  "Lighting",
  "Suspension",
  "Service",
  "Body",
  "Performance",
] as const;

export const yards: Yard[] = [
  {
    id: "apex",
    name: "Apex Motors",
    city: "Nairobi",
    location: "Industrial Area, Enterprise Rd",
    kind: "Yard",
    established: 2014,
    bio: "Import-led Toyota and Subaru yard. Auction sheets on every unit, duty-paid paper trail, and a workshop that actually answers the phone.",
    listings: 8,
    rating: 4.8,
    speciality: "Japanese imports",
  },
  {
    id: "thika",
    name: "Thika Road Auto Gallery",
    city: "Nairobi",
    location: "Roysambu, Thika Superhighway",
    kind: "Dealer",
    established: 2018,
    bio: "Family SUVs and town cars, inspected and photographed in daylight. Finance intro on request through the 88Motor Stores desk.",
    listings: 6,
    rating: 4.6,
    speciality: "Family SUVs",
  },
  {
    id: "coastline",
    name: "Coastline Motors",
    city: "Mombasa",
    location: "Nyali, Links Rd",
    kind: "Yard",
    established: 2011,
    bio: "Salt-air specialists. We underseal, we do not hide rust, and we know which engines hate the humid coast.",
    listings: 4,
    rating: 4.7,
    speciality: "Coastal-ready",
  },
  {
    id: "rift",
    name: "Rift Autos",
    city: "Nakuru",
    location: "Kenyatta Avenue",
    kind: "Yard",
    established: 2016,
    bio: "Workhorses for the highlands — Hilux, D-Max, Prado. Honest mileage, highland service history.",
    listings: 3,
    rating: 4.5,
    speciality: "Pickups & 4x4",
  },
  {
    id: "westlands",
    name: "Westlands Prestige",
    city: "Nairobi",
    location: "Westlands, Ring Rd",
    kind: "Dealer",
    established: 2009,
    bio: "German and British metal with service books. Quiet yard, no shouting, no weekend circus.",
    listings: 4,
    rating: 4.9,
    speciality: "Prestige",
  },
  {
    id: "private-nbo",
    name: "Private seller · Nairobi",
    city: "Nairobi",
    location: "Introduced via 88Motor Stores desk",
    kind: "Private",
    established: 2024,
    bio: "Private owner. The desk handles the first conversation so neither side trades phone numbers in public.",
    listings: 2,
    rating: 4.4,
    speciality: "One-owner",
  },
];

const IMG = {
  hero: "/images/hero.jpg",
  prado: "/images/cars/prado.jpg",
  wrx: "/images/cars/wrx.jpg",
  vitz: "/images/cars/vitz.jpg",
  cruiser: "/images/cars/cruiser.jpg",
  hilux: "/images/cars/hilux.jpg",
  bmw: "/images/cars/bmw.jpg",
  merc: "/images/cars/merc.jpg",
  cx5: "/images/cars/cx5.jpg",
  harrier: "/images/cars/harrier.jpg",
};

export const cars: Car[] = [
  {
    id: "prado-tx-2017",
    title: "Toyota Land Cruiser Prado TX",
    make: "Toyota",
    model: "Land Cruiser Prado",
    trim: "TX 7-seater",
    year: 2017,
    price: 5_650_000,
    marketValue: 5_900_000,
    mileage: 86_400,
    fuel: "Diesel",
    transmission: "Automatic",
    body: "SUV",
    color: "Pearl white",
    city: "Nairobi",
    location: "Industrial Area",
    origin: "Import",
    auctionGrade: "4.5",
    dutyPaid: true,
    owners: 1,
    engine: "2.8L 1GD-FTV turbo diesel",
    features: ["Sunroof", "Leather", "Crawl control", "360 camera", "Cool box"],
    description:
      "TX seven-seater, Japan import, auction 4.5. Service from Toyota Kenya on the last two intervals. No off-road scars on the sills. Third row unused. Ready for Mombasa road tomorrow.",
    image: IMG.prado,
    gallery: [IMG.prado, IMG.cruiser, IMG.harrier, IMG.hero],
    sellerId: "apex",
    daysListed: 6,
    views: 1840,
    condition: "Excellent",
    featured: true,
    demand: 92,
  },
  {
    id: "wrx-sti-2014",
    title: "Subaru Impreza WRX STI",
    make: "Subaru",
    model: "Impreza WRX",
    trim: "STI",
    year: 2014,
    price: 1_890_000,
    marketValue: 1_750_000,
    mileage: 112_000,
    fuel: "Petrol",
    transmission: "Manual",
    body: "Sedan",
    color: "World rally blue",
    city: "Nairobi",
    location: "Ngong Road",
    origin: "Import",
    auctionGrade: "4",
    dutyPaid: true,
    owners: 2,
    engine: "2.5L turbo EJ257",
    features: ["DCCD", "Recaro seats", "Brembo", "STI lip", "Boost gauge"],
    description:
      "Unmolested STI. Stock exhaust, no launch-control stories. Timing belt done at 105k. This is a driver's car, not a Saturday night project. Priced a touch above market because the body is straight and the DCCD works.",
    image: IMG.wrx,
    gallery: [IMG.wrx, IMG.bmw, IMG.vitz],
    sellerId: "apex",
    daysListed: 11,
    views: 3210,
    condition: "Very good",
    featured: true,
    demand: 88,
  },
  {
    id: "vitz-2017",
    title: "Toyota Vitz",
    make: "Toyota",
    model: "Vitz",
    trim: "1.3 F",
    year: 2017,
    price: 890_000,
    marketValue: 920_000,
    mileage: 64_200,
    fuel: "Petrol",
    transmission: "Automatic",
    body: "Hatchback",
    color: "Silver",
    city: "Nairobi",
    location: "South B",
    origin: "Import",
    auctionGrade: "4.5",
    dutyPaid: true,
    owners: 1,
    engine: "1.3L 1NR-FE",
    features: ["Keyless", "Reverse camera", "Eco idle", "Alloy wheels"],
    description:
      "The Kenyan hatch done properly. One owner since the port, city mileage, no taxi history. Ideal first car or a quiet second car for town.",
    image: IMG.vitz,
    gallery: [IMG.vitz, IMG.harrier, IMG.cx5],
    sellerId: "thika",
    daysListed: 4,
    views: 980,
    condition: "Excellent",
    featured: true,
    demand: 95,
  },
  {
    id: "lc300-2022",
    title: "Toyota Land Cruiser 300 ZX",
    make: "Toyota",
    model: "Land Cruiser 300",
    trim: "ZX",
    year: 2022,
    price: 18_400_000,
    marketValue: 18_900_000,
    mileage: 28_600,
    fuel: "Diesel",
    transmission: "Automatic",
    body: "SUV",
    color: "Beige",
    city: "Nairobi",
    location: "Westlands",
    origin: "Import",
    auctionGrade: "4.5",
    dutyPaid: true,
    owners: 1,
    engine: "3.3L V6 twin-turbo diesel",
    features: [
      "Multi-terrain monitor",
      "Cool box",
      "JBL audio",
      "Rear entertainment",
      "Crawl control",
    ],
    description:
      "ZX in beige — the safari colour. Low kilometres, still on factory tyres with even wear. Books with Toyota Kenya. This is a long-stay car, not a flip.",
    image: IMG.cruiser,
    gallery: [IMG.cruiser, IMG.prado, IMG.hero],
    sellerId: "westlands",
    daysListed: 18,
    views: 2640,
    condition: "Excellent",
    featured: true,
    demand: 80,
  },
  {
    id: "hilux-2020",
    title: "Toyota Hilux Double Cab",
    make: "Toyota",
    model: "Hilux",
    trim: "SR5 2.8D",
    year: 2020,
    price: 6_150_000,
    marketValue: 6_000_000,
    mileage: 74_800,
    fuel: "Diesel",
    transmission: "Automatic",
    body: "Pickup",
    color: "White",
    city: "Nakuru",
    location: "Kenyatta Avenue",
    origin: "Local",
    dutyPaid: true,
    owners: 1,
    engine: "2.8L 1GD-FTV",
    features: ["Diff lock", "Tonneau", "Sports bar", "Reverse camera", "Hill descent"],
    description:
      "Local-spec SR5, one company owner, full Toyota service. Load bed lined, no farm abuse. Ready for site, farm, or a well-behaved weekend.",
    image: IMG.hilux,
    gallery: [IMG.hilux, IMG.cruiser, IMG.prado],
    sellerId: "rift",
    daysListed: 9,
    views: 1540,
    condition: "Very good",
    demand: 86,
  },
  {
    id: "bmw-320i-2016",
    title: "BMW 320i M Sport",
    make: "BMW",
    model: "3 Series",
    trim: "320i M Sport",
    year: 2016,
    price: 2_780_000,
    marketValue: 2_850_000,
    mileage: 79_400,
    fuel: "Petrol",
    transmission: "Automatic",
    body: "Sedan",
    color: "Black sapphire",
    city: "Nairobi",
    location: "Westlands",
    origin: "Import",
    auctionGrade: "4",
    dutyPaid: true,
    owners: 2,
    engine: "2.0L turbo B48",
    features: ["M Sport pack", "Harman Kardon", "Sunroof", "Adaptive LED", "Sport seats"],
    description:
      "B48 320i — the reliable one. Service history with a Westlands independent that only does BMW. Pads and discs at 72k. No drift-day rumours.",
    image: IMG.bmw,
    gallery: [IMG.bmw, IMG.merc, IMG.wrx],
    sellerId: "westlands",
    daysListed: 7,
    views: 1210,
    condition: "Very good",
    featured: true,
    demand: 74,
  },
  {
    id: "c200-2017",
    title: "Mercedes-Benz C200",
    make: "Mercedes-Benz",
    model: "C-Class",
    trim: "C200 Exclusive",
    year: 2017,
    price: 3_420_000,
    marketValue: 3_500_000,
    mileage: 68_900,
    fuel: "Petrol",
    transmission: "Automatic",
    body: "Sedan",
    color: "Polar silver",
    city: "Nairobi",
    location: "Westlands",
    origin: "Import",
    auctionGrade: "4.5",
    dutyPaid: true,
    owners: 1,
    engine: "2.0L turbo M274",
    features: [
      "Burmester",
      "Panoramic roof",
      "Airscarf",
      "LED intelligent",
      "Memory seats",
    ],
    description:
      "W205 Exclusive in polar silver. One private owner, dealer-serviced until 2024 then an independent with invoices. Quiet, cold A/C, no gearbox kick.",
    image: IMG.merc,
    gallery: [IMG.merc, IMG.bmw, IMG.hero],
    sellerId: "westlands",
    daysListed: 13,
    views: 990,
    condition: "Excellent",
    demand: 71,
  },
  {
    id: "cx5-2018",
    title: "Mazda CX-5 AWD",
    make: "Mazda",
    model: "CX-5",
    trim: "AWD diesel",
    year: 2018,
    price: 2_680_000,
    marketValue: 2_750_000,
    mileage: 71_200,
    fuel: "Diesel",
    transmission: "Automatic",
    body: "Crossover",
    color: "Soul red",
    city: "Mombasa",
    location: "Nyali",
    origin: "Import",
    auctionGrade: "4.5",
    dutyPaid: true,
    owners: 1,
    engine: "2.2L Skyactiv-D",
    features: ["AWD", "Bose", "Heads-up", "Leather", "Radar cruise"],
    description:
      "Soul red on the coast, undersealed last year. Skyactiv-D with DPF health confirmed. AWD for rainy season, not a poser extra.",
    image: IMG.cx5,
    gallery: [IMG.cx5, IMG.harrier, IMG.prado],
    sellerId: "coastline",
    daysListed: 5,
    views: 870,
    condition: "Excellent",
    featured: true,
    demand: 83,
  },
  {
    id: "harrier-2018",
    title: "Toyota Harrier",
    make: "Toyota",
    model: "Harrier",
    trim: "Premium",
    year: 2018,
    price: 3_150_000,
    marketValue: 3_250_000,
    mileage: 58_400,
    fuel: "Petrol",
    transmission: "Automatic",
    body: "Crossover",
    color: "White pearl",
    city: "Nairobi",
    location: "Roysambu",
    origin: "Import",
    auctionGrade: "4.5",
    dutyPaid: true,
    owners: 1,
    engine: "2.0L 8AR-FTS turbo",
    features: ["Panoramic roof", "JBL", "Power tailgate", "360 camera", "Leather"],
    description:
      "The Nairobi default, done well. Premium grade, panoramic roof, no Uber history. Turbo 8AR with a clean service sheet.",
    image: IMG.harrier,
    gallery: [IMG.harrier, IMG.prado, IMG.cx5],
    sellerId: "thika",
    daysListed: 3,
    views: 2104,
    condition: "Excellent",
    featured: true,
    demand: 97,
  },
  {
    id: "markx-2015",
    title: "Toyota Mark X",
    make: "Toyota",
    model: "Mark X",
    trim: "250G",
    year: 2015,
    price: 1_620_000,
    marketValue: 1_580_000,
    mileage: 98_700,
    fuel: "Petrol",
    transmission: "Automatic",
    body: "Sedan",
    color: "Black",
    city: "Nairobi",
    location: "Eastlands",
    origin: "Import",
    auctionGrade: "4",
    dutyPaid: true,
    owners: 2,
    engine: "2.5L 4GR-FSE",
    features: ["Smart key", "Sunroof", "Paddle shift", "HID", "Rear spoiler"],
    description:
      "Clean 250G. Not a 350 with a loud exhaust. Suspension original, no stretched tyres. Priced at market for a car that still feels tight.",
    image: IMG.bmw,
    gallery: [IMG.bmw, IMG.wrx, IMG.merc],
    sellerId: "apex",
    daysListed: 16,
    views: 1430,
    condition: "Very good",
    demand: 78,
  },
  {
    id: "fielder-2016",
    title: "Toyota Fielder",
    make: "Toyota",
    model: "Fielder",
    trim: "Hybrid",
    year: 2016,
    price: 1_280_000,
    marketValue: 1_320_000,
    mileage: 91_100,
    fuel: "Hybrid",
    transmission: "Automatic",
    body: "Wagon",
    color: "Silver",
    city: "Thika",
    location: "Makongeni",
    origin: "Import",
    auctionGrade: "4",
    dutyPaid: true,
    owners: 1,
    engine: "1.5L 1NZ-FXE hybrid",
    features: ["Hybrid", "Roof rails", "Reverse camera", "Fog lamps"],
    description:
      "The workhorse wagon. Hybrid battery tested, inverter quiet. Perfect for a Thika–Nairobi commute without burning a hole in the month.",
    image: IMG.vitz,
    gallery: [IMG.vitz, IMG.harrier, IMG.cx5],
    sellerId: "thika",
    daysListed: 8,
    views: 760,
    condition: "Very good",
    demand: 84,
  },
  {
    id: "xtrail-2017",
    title: "Nissan X-Trail",
    make: "Nissan",
    model: "X-Trail",
    trim: "20X Hybrid",
    year: 2017,
    price: 2_120_000,
    marketValue: 2_180_000,
    mileage: 82_300,
    fuel: "Hybrid",
    transmission: "Automatic",
    body: "SUV",
    color: "Graphite",
    city: "Eldoret",
    location: "Uganda Road",
    origin: "Import",
    auctionGrade: "4",
    dutyPaid: true,
    owners: 1,
    engine: "2.0L hybrid",
    features: ["7 seats", "Around view", "Roof rails", "Power tailgate"],
    description:
      "Seven seats for highland school runs. Hybrid for town, ground clearance for the murram last kilometre. Eldoret-based, never a taxi.",
    image: IMG.cx5,
    gallery: [IMG.cx5, IMG.prado, IMG.harrier],
    sellerId: "rift",
    daysListed: 12,
    views: 640,
    condition: "Very good",
    demand: 69,
  },
  {
    id: "fit-2018",
    title: "Honda Fit",
    make: "Honda",
    model: "Fit",
    trim: "Hybrid F",
    year: 2018,
    price: 1_140_000,
    marketValue: 1_180_000,
    mileage: 55_600,
    fuel: "Hybrid",
    transmission: "Automatic",
    body: "Hatchback",
    color: "White",
    city: "Nairobi",
    location: "Kileleshwa",
    origin: "Import",
    auctionGrade: "4.5",
    dutyPaid: true,
    owners: 1,
    engine: "1.5L hybrid",
    features: ["Magic seats", "Honda sensing", "Keyless", "Camera"],
    description:
      "Low-kilometre Fit hybrid. Magic seats still click. Sensing pack intact. A civilised town car with Honda reliability.",
    image: IMG.vitz,
    gallery: [IMG.vitz, IMG.harrier],
    sellerId: "private-nbo",
    daysListed: 2,
    views: 410,
    condition: "Excellent",
    demand: 81,
  },
  {
    id: "rangerover-2015",
    title: "Range Rover Sport HSE",
    make: "Land Rover",
    model: "Range Rover Sport",
    trim: "HSE",
    year: 2015,
    price: 6_850_000,
    marketValue: 7_100_000,
    mileage: 94_200,
    fuel: "Diesel",
    transmission: "Automatic",
    body: "SUV",
    color: "Santorini black",
    city: "Nairobi",
    location: "Karen",
    origin: "Import",
    dutyPaid: true,
    owners: 2,
    engine: "3.0L SDV6",
    features: ["Meridian", "Air suspension", "Panoramic", "Terrain Response", "Cool box"],
    description:
      "HSE with recent air springs and a documented timing-belt job. Not a cheap Range Rover story — the expensive bits have already been done.",
    image: IMG.hero,
    gallery: [IMG.hero, IMG.cruiser, IMG.prado],
    sellerId: "westlands",
    daysListed: 21,
    views: 1880,
    condition: "Good",
    demand: 62,
  },
  {
    id: "demio-2017",
    title: "Mazda Demio",
    make: "Mazda",
    model: "Demio",
    trim: "XD touring",
    year: 2017,
    price: 980_000,
    marketValue: 1_020_000,
    mileage: 72_400,
    fuel: "Diesel",
    transmission: "Automatic",
    body: "Hatchback",
    color: "Soul red",
    city: "Mombasa",
    location: "Bamburi",
    origin: "Import",
    auctionGrade: "4.5",
    dutyPaid: true,
    owners: 1,
    engine: "1.5L Skyactiv-D",
    features: ["Heads-up", "Bose", "Smart city brake", "Alloys"],
    description:
      "Diesel Demio that sips on the highway to Malindi. Heads-up still bright. Undersealed. A grown-up alternative to a Vitz.",
    image: IMG.cx5,
    gallery: [IMG.cx5, IMG.vitz],
    sellerId: "coastline",
    daysListed: 6,
    views: 530,
    condition: "Excellent",
    demand: 77,
  },
  {
    id: "dmax-2019",
    title: "Isuzu D-Max",
    make: "Isuzu",
    model: "D-Max",
    trim: "LS 4x4",
    year: 2019,
    price: 3_750_000,
    marketValue: 3_820_000,
    mileage: 88_600,
    fuel: "Diesel",
    transmission: "Manual",
    body: "Pickup",
    color: "White",
    city: "Nakuru",
    location: "Industrial area",
    origin: "Local",
    dutyPaid: true,
    owners: 1,
    engine: "3.0L 4JJ1",
    features: ["4x4", "Diff lock", "Tow bar", "Bed liner"],
    description:
      "The 4JJ1 that just keeps going. Farm and site use, not beaten. Gearbox is the five-speed you want. Ready to work Monday.",
    image: IMG.hilux,
    gallery: [IMG.hilux, IMG.cruiser],
    sellerId: "rift",
    daysListed: 10,
    views: 720,
    condition: "Very good",
    demand: 73,
  },
  {
    id: "forester-2017",
    title: "Subaru Forester",
    make: "Subaru",
    model: "Forester",
    trim: "XT",
    year: 2017,
    price: 2_380_000,
    marketValue: 2_450_000,
    mileage: 77_900,
    fuel: "Petrol",
    transmission: "Automatic",
    body: "SUV",
    color: "Dark grey",
    city: "Nairobi",
    location: "Ngong Road",
    origin: "Import",
    auctionGrade: "4",
    dutyPaid: true,
    owners: 1,
    engine: "2.0L turbo FA20",
    features: ["X-Mode", "Eyesight", "Sunroof", "Power tailgate"],
    description:
      "XT turbo Forester with Eyesight. Timing chain engine, so no belt stories. AWD that actually sees rain. Subaru Nation favourite.",
    image: IMG.wrx,
    gallery: [IMG.wrx, IMG.prado, IMG.harrier],
    sellerId: "apex",
    daysListed: 14,
    views: 1104,
    condition: "Very good",
    demand: 79,
  },
  {
    id: "premio-2016",
    title: "Toyota Premio",
    make: "Toyota",
    model: "Premio",
    trim: "1.8 F",
    year: 2016,
    price: 1_480_000,
    marketValue: 1_520_000,
    mileage: 83_200,
    fuel: "Petrol",
    transmission: "Automatic",
    body: "Sedan",
    color: "White pearl",
    city: "Kisumu",
    location: "Oginga Odinga St",
    origin: "Import",
    auctionGrade: "4",
    dutyPaid: true,
    owners: 1,
    engine: "1.8L 2ZR-FAE",
    features: ["Smart key", "Camera", "Dual A/C", "Fog lamps"],
    description:
      "Lakeside Premio, no taxi roof holes, no yellow interior. A quiet saloon for someone who is done with hatches.",
    image: IMG.merc,
    gallery: [IMG.merc, IMG.bmw, IMG.vitz],
    sellerId: "coastline",
    daysListed: 19,
    views: 480,
    condition: "Very good",
    demand: 70,
  },
  {
    id: "golf-gti-2016",
    title: "Volkswagen Golf GTI",
    make: "Volkswagen",
    model: "Golf",
    trim: "GTI",
    year: 2016,
    price: 2_450_000,
    marketValue: 2_520_000,
    mileage: 81_500,
    fuel: "Petrol",
    transmission: "Automatic",
    body: "Hatchback",
    color: "Tornado red",
    city: "Nairobi",
    location: "Kilimani",
    origin: "Import",
    dutyPaid: true,
    owners: 2,
    engine: "2.0L TSI",
    features: ["DCC", "Calipers red", "Discover pro", "Sunroof"],
    description:
      "Mk7 GTI with DSG serviced and mechatronic oil done. Not a stage-2 experiment. Red calipers original. Fun without the STI tax.",
    image: IMG.wrx,
    gallery: [IMG.wrx, IMG.vitz, IMG.bmw],
    sellerId: "private-nbo",
    daysListed: 15,
    views: 890,
    condition: "Very good",
    demand: 66,
  },
  {
    id: "crv-2018",
    title: "Honda CR-V",
    make: "Honda",
    model: "CR-V",
    trim: "EX-L",
    year: 2018,
    price: 3_050_000,
    marketValue: 3_120_000,
    mileage: 61_800,
    fuel: "Petrol",
    transmission: "Automatic",
    body: "Crossover",
    color: "White",
    city: "Nairobi",
    location: "Roysambu",
    origin: "Import",
    auctionGrade: "4.5",
    dutyPaid: true,
    owners: 1,
    engine: "1.5L VTEC turbo",
    features: ["Leather", "Honda sensing", "Power tailgate", "Sunroof"],
    description:
      "EX-L turbo CR-V. Sensing pack, leather still tight. The sensible rival to a Harrier if you want Honda service intervals.",
    image: IMG.harrier,
    gallery: [IMG.harrier, IMG.cx5, IMG.prado],
    sellerId: "thika",
    daysListed: 7,
    views: 930,
    condition: "Excellent",
    demand: 82,
  },
];

export const parts: Part[] = [
  {
    id: "tyres-at-265",
    title: "All-terrain tyres 265/65 R17 · set of 4",
    brand: "RoadForge",
    category: "Tyres & wheels",
    price: 86_000,
    condition: "New",
    fitment: ["Hilux", "Prado", "Fortuner", "D-Max"],
    city: "Nairobi",
    location: "Industrial Area",
    image: "/images/parts/tyres.jpg",
    crop: "img-wheel",
    description:
      "Four new all-terrains, 2025 week codes. Balanced and ready for a Hilux or Prado. We fit on site; old tyres taken if you want.",
    sellerId: "apex",
    stock: 6,
    oem: "265/65R17",
  },
  {
    id: "brakes-prado",
    title: "Prado 150 front discs & pads",
    brand: "Akebono spec",
    category: "Brakes",
    price: 24_500,
    condition: "New",
    fitment: ["Land Cruiser Prado 150"],
    city: "Nairobi",
    location: "Industrial Area",
    image: "/images/parts/suspension.jpg",
    crop: "img-low",
    description:
      "Ventilated discs and ceramic pads for the 150. No spongy pedal stories. Comes with fitting clips.",
    sellerId: "apex",
    stock: 11,
    oem: "43512-60150",
  },
  {
    id: "lamps-bmw-f30",
    title: "F30 LED projector headlamps · pair",
    brand: "OEM-style",
    category: "Lighting",
    price: 78_000,
    condition: "Refurbished",
    fitment: ["BMW 3 Series F30"],
    city: "Nairobi",
    location: "Westlands",
    image: "/images/parts/lamps.jpg",
    crop: "img-lamp",
    description:
      "Refurbished projectors, new lenses, coded-ready. Not the cheap chrome-bowl copies. Deposit via the desk.",
    sellerId: "westlands",
    stock: 2,
  },
  {
    id: "turbo-1gd",
    title: "1GD-FTV turbocharger",
    brand: "IHI spec",
    category: "Engine",
    price: 145_000,
    condition: "Refurbished",
    fitment: ["Hilux", "Prado", "Fortuner 2.8D"],
    city: "Nairobi",
    location: "Industrial Area",
    image: "/images/parts/performance.jpg",
    crop: "img-front",
    description:
      "Rebuilt 1GD turbo, new cartridge, balanced. Six-month desk-backed warranty if fitted at a listed workshop.",
    sellerId: "apex",
    stock: 3,
    oem: "17201-0E040",
  },
  {
    id: "suspension-vitz",
    title: "Vitz / Demio lowering springs",
    brand: "Tanabe-style",
    category: "Suspension",
    price: 18_500,
    condition: "New",
    fitment: ["Vitz", "Demio", "Fit"],
    city: "Nairobi",
    location: "Ngong Road",
    image: "/images/parts/suspension.jpg",
    crop: "img-cover",
    description:
      "Mild 30mm drop. Keeps the daily-driver ride. Popular in Vitz Nation — we have the fitting torque spec on file.",
    sellerId: "apex",
    stock: 8,
  },
  {
    id: "service-kit-b48",
    title: "BMW B48 major service kit",
    brand: "Mahle / Mann",
    category: "Service",
    price: 32_000,
    condition: "New",
    fitment: ["BMW 320i B48", "X1 20i"],
    city: "Nairobi",
    location: "Westlands",
    image: "/images/parts/service.jpg",
    crop: "img-cover",
    description:
      "Oil filter, air, cabin, plugs, and drain plug. The kit independents actually use. Oil not included — specify 0W-20 or 5W-30 when you enquire.",
    sellerId: "westlands",
    stock: 14,
  },
  {
    id: "sti-lip",
    title: "STI-style front lip · GRB/GVB",
    brand: "Chargespeed-style",
    category: "Body",
    price: 27_000,
    condition: "New",
    fitment: ["Impreza WRX STI 2008–2014"],
    city: "Nairobi",
    location: "Ngong Road",
    image: "/images/parts/body.jpg",
    crop: "img-front",
    description:
      "PU lip, primed, ready for paint. Sits correctly on an original bumper — not the universal ‘almost’.",
    sellerId: "apex",
    stock: 4,
  },
  {
    id: "battery-ns70",
    title: "NS70 sealed battery",
    brand: "VoltHaus",
    category: "Service",
    price: 16_800,
    condition: "New",
    fitment: ["Prado", "Hilux", "Harrier", "CX-5"],
    city: "Mombasa",
    location: "Nyali",
    image: "/images/parts/service.jpg",
    crop: "img-low",
    description:
      "Sealed NS70, 18-month replacement through the desk. We test-fit CCA before you leave the yard.",
    sellerId: "coastline",
    stock: 20,
  },
  {
    id: "oil-5w30",
    title: "Fully synthetic 5W-30 · 20L drum",
    brand: "NorthRidge",
    category: "Service",
    price: 22_400,
    condition: "New",
    fitment: ["Most petrol Toyotas", "Subaru FB/FA"],
    city: "Nairobi",
    location: "Industrial Area",
    image: "/images/parts/coast.jpg",
    crop: "img-cover",
    description:
      "Workshop drum, API SN. For yards doing volume. We do not split litres on this listing.",
    sellerId: "apex",
    stock: 9,
  },
  {
    id: "headlamp-harrier",
    title: "Harrier 60 LED DRL strip · pair",
    brand: "OEM-style",
    category: "Lighting",
    price: 41_000,
    condition: "New",
    fitment: ["Toyota Harrier 60"],
    city: "Nairobi",
    location: "Roysambu",
    image: "/images/parts/lamps.jpg",
    crop: "img-lamp",
    description:
      "Sequential DRL housings. Plug and play on 60-series. Bring the car — alignment is included in the intro.",
    sellerId: "thika",
    stock: 5,
  },
  {
    id: "pads-vitz",
    title: "Vitz / Axio front pads",
    brand: "Akebono spec",
    category: "Brakes",
    price: 4_800,
    condition: "New",
    fitment: ["Vitz", "Axio", "Fielder", "Premio"],
    city: "Thika",
    location: "Makongeni",
    image: "/images/parts/tyres.jpg",
    crop: "img-low",
    description:
      "Everyday pads that do not dust the 15-inch steels. A Vitz Nation staple.",
    sellerId: "thika",
    stock: 40,
  },
  {
    id: "coilovers-wrx",
    title: "Adjustable coilovers · WRX/STI",
    brand: "Tein-style",
    category: "Performance",
    price: 95_000,
    condition: "Used",
    fitment: ["Impreza WRX", "STI GRB"],
    city: "Nairobi",
    location: "Ngong Road",
    image: "/images/parts/performance.jpg",
    crop: "img-cover",
    description:
      "Used 16-way coilovers, 18k km on them, no leaks. Comes with helper springs. Inspection at the yard before the desk connects you.",
    sellerId: "apex",
    stock: 1,
  },
];

export const nations: Nation[] = [
  {
    slug: "subaru-nation",
    name: "Subaru Nation KE",
    tagline: "AWD, hood scoops, and Saturday morning meets.",
    make: "Subaru",
    members: 12840,
    cover: "/images/nations/subaru.jpg",
    about:
      "The oldest continuous Subaru board in Kenya. WRX, Forester, Legacy, XV. We talk boost, we talk timing belts, we do not talk staged photos of borrowed cars.",
    rules: [
      "No selling in the main feed — list on 88Motor Stores and link the stock.",
      "Meet points posted 48 hours out. No rolling 80 on Ngong Road.",
      "Technical advice is peer-to-peer, not a warranty.",
    ],
    threads: [
      {
        id: "s1",
        title: "Where are we meeting this Sunday — The Hub or Two Rivers?",
        author: "Wanjiku.sti",
        excerpt:
          "Last month Two Rivers was packed and security got twitchy. Hub Karen has the overflow. Votes below.",
        replies: 86,
        likes: 210,
        time: "2h ago",
        pinned: true,
      },
      {
        id: "s2",
        title: "EJ257 knock on 95 — is Total energies 95 enough in Nairobi?",
        author: "OtienoBoost",
        excerpt:
          "Pinging on the Thika superhighway pull. Map is stock. Who is running 98 and from which station?",
        replies: 54,
        likes: 132,
        time: "5h ago",
      },
      {
        id: "s3",
        title: "STI springs that do not destroy the daily.",
        author: "NakuruBoxer",
        excerpt:
          "Need a 20–25mm drop that still eats Mombasa road expansion joints. Tanabe? RSR? Keep it street.",
        replies: 41,
        likes: 98,
        time: "1d ago",
      },
      {
        id: "s4",
        title: "Forester XT vs Prado for a Naivasha weekend house.",
        author: "AminaXT",
        excerpt:
          "I know this is heresy. Hear me out: budget is 2.5. Dust, murram last 3km, two kids.",
        replies: 73,
        likes: 160,
        time: "2d ago",
      },
    ],
  },
  {
    slug: "vitz-nation",
    name: "Vitz Nation",
    tagline: "The people’s hatch. Town, traffic, no drama.",
    make: "Toyota",
    members: 24100,
    cover: "/images/nations/vitz.jpg",
    about:
      "Vitz, Demio, Fit, Passo — the cars that actually move Nairobi. Fuel, hire-purchase, first-car mistakes, and how not to buy a taxi.",
    rules: [
      "Post the year and engine when asking ‘is this a good price’.",
      "No shame for 1300s. Most of us started there.",
      "Introduce sales through 88Motor Stores — DMs for deals get you muted.",
    ],
    threads: [
      {
        id: "v1",
        title: "2017 1.3 F at 890k — 88Motor Stores has it. Thoughts?",
        author: "KendiFirstCar",
        excerpt:
          "Auction 4.5, 64k km, South B. First car. Do I still inspect or is the grade enough?",
        replies: 122,
        likes: 340,
        time: "40m ago",
        pinned: true,
      },
      {
        id: "v2",
        title: "1300 vs 1500 for Ngong–town every day.",
        author: "BrianCommute",
        excerpt:
          "Hills on the way home. A/C on. CVT. Who regrets the 1300?",
        replies: 67,
        likes: 154,
        time: "4h ago",
      },
      {
        id: "v3",
        title: "Hire-purchase yards to avoid this month.",
        author: "AchiengBooks",
        excerpt:
          "If the logbook stays with a ‘broker’ for 18 months, walk. Names in the replies, evidence only.",
        replies: 91,
        likes: 410,
        time: "1d ago",
      },
    ],
  },
  {
    slug: "prado-cruiser",
    name: "Prado & Cruiser Club",
    tagline: "Diesel, crawl control, and the Mombasa road.",
    make: "Toyota",
    members: 9320,
    cover: "/images/nations/prado.jpg",
    about:
      "150, 120, 200, 300. Safari prep, injector health, and which TX is actually a TZ in disguise. We take the long way.",
    rules: [
      "Fuel figures with route, load, and A/C — or they do not count.",
      "No ‘flex’ parking-lot shots without a question attached.",
      "Convoy rules on public roads. Always.",
    ],
    threads: [
      {
        id: "p1",
        title: "Nairobi–Mombasa in a 150 diesel: 11.8L/100km loaded.",
        author: "JumaTX",
        excerpt:
          "Seven seats, roof box, two adults. 80–100 indicated. Shell on the highway. Beat that with honesty.",
        replies: 48,
        likes: 176,
        time: "3h ago",
        pinned: true,
      },
      {
        id: "p2",
        title: "300 ZX beige on 88Motor Stores — who has seen this one in Westlands?",
        author: "SafariKate",
        excerpt:
          "28k km, books. I want a second pair of eyes on the underbody before I request the intro.",
        replies: 29,
        likes: 88,
        time: "8h ago",
      },
      {
        id: "p3",
        title: "1GD turbo rebuild — Apex has a unit listed.",
        author: "KitalePrado",
        excerpt:
          "Whistle on boost after 180k. Has anyone used that refurbished IHI through the desk?",
        replies: 36,
        likes: 72,
        time: "2d ago",
      },
    ],
  },
  {
    slug: "bmw-club",
    name: "BMW Club Nairobi",
    tagline: "B48s, independents, and no surprise oil leaks.",
    make: "BMW",
    members: 4180,
    cover: "/images/nations/bmw.jpg",
    about:
      "F30, G20, X5. We talk independents that keep German cars alive in Kenyan heat, not dealership theatre.",
    rules: [
      "Post the engine code. ‘320i’ is not a diagnosis.",
      "Independent recs need a suburb and a bill photo, not vibes.",
      "Sales through 88Motor Stores only.",
    ],
    threads: [
      {
        id: "b1",
        title: "Westlands independents who will not invent jobs.",
        author: "MwangiF30",
        excerpt:
          "Need pads, oil, and an honest scan. Last place tried to sell me a transfer case for a RWD 320i.",
        replies: 58,
        likes: 201,
        time: "6h ago",
        pinned: true,
      },
      {
        id: "b2",
        title: "M Sport 2016 on 88Motor Stores — B48, 79k.",
        author: "LisaKilimani",
        excerpt:
          "Looks straight. Who has dealt with Westlands Prestige on intros?",
        replies: 22,
        likes: 64,
        time: "1d ago",
      },
    ],
  },
  {
    slug: "pickup-yard",
    name: "Pickup Yard",
    tagline: "Hilux, D-Max, work, farm, no chrome festivals.",
    make: "Toyota",
    members: 7760,
    cover: "/images/nations/hilux.jpg",
    about:
      "Double cabs that work. Load ratings, farm miles, and which ‘SR5’ is actually an S.",
    rules: [
      "State 4x2 or 4x4 in the title.",
      "Company cars need service stamps.",
      "No bull-bar flex without a use case.",
    ],
    threads: [
      {
        id: "h1",
        title: "Nakuru SR5 2020 vs D-Max 2019 for a flower farm.",
        author: "NaivashaBeds",
        excerpt:
          "Mud, crates, 4am starts. Reliability over badge. Both are on 88Motor Stores this week.",
        replies: 44,
        likes: 119,
        time: "5h ago",
        pinned: true,
      },
      {
        id: "h2",
        title: "All-terrain 265 set listed in Industrial Area.",
        author: "EldoretTreads",
        excerpt: "Need four this Friday. Anyone fitted RoadForge on a Hilux?",
        replies: 18,
        likes: 41,
        time: "1d ago",
      },
    ],
  },
  {
    slug: "prestige-ke",
    name: "Prestige KE",
    tagline: "Mercedes, Range Rover, quiet yards.",
    make: "Mercedes-Benz",
    members: 2890,
    cover: "/images/nations/prestige.jpg",
    about:
      "For people who want the car, not the circus. Service books, air springs, and which C-Class is still a good idea.",
    rules: [
      "Maintenance receipts or it did not happen.",
      "No ‘CEO package’ language.",
      "Desk intros only — no valet-parking business cards in threads.",
    ],
    threads: [
      {
        id: "r1",
        title: "W205 C200 Exclusive — polar silver on the floor.",
        author: "AishaWestlands",
        excerpt:
          "One owner, panoramic. Anyone know the independent that did the last service?",
        replies: 16,
        likes: 47,
        time: "9h ago",
        pinned: true,
      },
      {
        id: "r2",
        title: "Range Rover Sport 2015 — air springs already done.",
        author: "KarenDrive",
        excerpt:
          "The expensive surprise is apparently behind it. Still want a PPI. Who in Karen does Land Rover without inventing faults?",
        replies: 27,
        likes: 83,
        time: "2d ago",
      },
    ],
  },
];

export const marketSeries = [
  { month: "Mar", toyota: 2.1, subaru: 1.8, mazda: 1.6, bmw: 2.9 },
  { month: "Apr", toyota: 2.15, subaru: 1.82, mazda: 1.58, bmw: 2.85 },
  { month: "May", toyota: 2.22, subaru: 1.9, mazda: 1.62, bmw: 2.8 },
  { month: "Jun", toyota: 2.18, subaru: 1.95, mazda: 1.7, bmw: 2.78 },
  { month: "Jul", toyota: 2.3, subaru: 2.0, mazda: 1.72, bmw: 2.74 },
  { month: "Aug", toyota: 2.28, subaru: 2.05, mazda: 1.75, bmw: 2.76 },
  { month: "Sep", toyota: 2.35, subaru: 2.08, mazda: 1.78, bmw: 2.72 },
];

export function yardById(id: string) {
  return yards.find((y) => y.id === id);
}

export function carById(id: string) {
  return cars.find((c) => c.id === id);
}

export function partById(id: string) {
  return parts.find((p) => p.id === id);
}

export function nationBySlug(slug: string) {
  return nations.find((n) => n.slug === slug);
}

export function carsForYard(id: string) {
  return cars.filter((c) => c.sellerId === id);
}

export function partsForYard(id: string) {
  return parts.filter((p) => p.sellerId === id);
}
