/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as CarsRouteImport } from './routes/cars'
import { Route as CompareRouteImport } from './routes/compare'
import { Route as DeskRouteImport } from './routes/desk'
import { Route as GarageRouteImport } from './routes/garage'
import { Route as HowItWorksRouteImport } from './routes/how-it-works'
import { Route as InsightsRouteImport } from './routes/insights'
import { Route as LoginRouteImport } from './routes/login'
import { Route as NationsRouteImport } from './routes/nations'
import { Route as NotificationRouteImport } from './routes/notification'
import { Route as NotificationsRouteImport } from './routes/notifications'
import { Route as PartsRouteImport } from './routes/parts'
import { Route as SellRouteImport } from './routes/sell'
import { Route as SignUpRouteImport } from './routes/sign-up'
import { Route as CarsIndexRouteImport } from './routes/cars.index'
import { Route as CarsIdRouteImport } from './routes/cars.$id'
import { Route as ListingsIdRouteImport } from './routes/listings.$id'
import { Route as NationsIndexRouteImport } from './routes/nations.index'
import { Route as NationsSlugRouteImport } from './routes/nations.$slug'
import { Route as PartsIndexRouteImport } from './routes/parts.index'
import { Route as PartsIdRouteImport } from './routes/parts.$id'
import { Route as YardsIdRouteImport } from './routes/yards.$id'
import { Route as ApiAuthSplatRouteImport } from './routes/api/auth/$'
import { Route as NationsSlugIndexRouteImport } from './routes/nations.$slug.index'
import { Route as NationsSlugThreadIdRouteImport } from './routes/nations.$slug.$threadId'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const CarsRoute = CarsRouteImport.update({
  id: '/cars',
  path: '/cars',
  getParentRoute: () => rootRouteImport,
} as any)
const CompareRoute = CompareRouteImport.update({
  id: '/compare',
  path: '/compare',
  getParentRoute: () => rootRouteImport,
} as any)
const DeskRoute = DeskRouteImport.update({
  id: '/desk',
  path: '/desk',
  getParentRoute: () => rootRouteImport,
} as any)
const GarageRoute = GarageRouteImport.update({
  id: '/garage',
  path: '/garage',
  getParentRoute: () => rootRouteImport,
} as any)
const HowItWorksRoute = HowItWorksRouteImport.update({
  id: '/how-it-works',
  path: '/how-it-works',
  getParentRoute: () => rootRouteImport,
} as any)
const InsightsRoute = InsightsRouteImport.update({
  id: '/insights',
  path: '/insights',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const NationsRoute = NationsRouteImport.update({
  id: '/nations',
  path: '/nations',
  getParentRoute: () => rootRouteImport,
} as any)
const NotificationRoute = NotificationRouteImport.update({
  id: '/notification',
  path: '/notification',
  getParentRoute: () => rootRouteImport,
} as any)
const NotificationsRoute = NotificationsRouteImport.update({
  id: '/notifications',
  path: '/notifications',
  getParentRoute: () => rootRouteImport,
} as any)
const PartsRoute = PartsRouteImport.update({
  id: '/parts',
  path: '/parts',
  getParentRoute: () => rootRouteImport,
} as any)
const SellRoute = SellRouteImport.update({
  id: '/sell',
  path: '/sell',
  getParentRoute: () => rootRouteImport,
} as any)
const SignUpRoute = SignUpRouteImport.update({
  id: '/sign-up',
  path: '/sign-up',
  getParentRoute: () => rootRouteImport,
} as any)
const CarsIndexRoute = CarsIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => CarsRoute,
} as any)
const CarsIdRoute = CarsIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => CarsRoute,
} as any)
const ListingsIdRoute = ListingsIdRouteImport.update({
  id: '/listings/$id',
  path: '/listings/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const NationsIndexRoute = NationsIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => NationsRoute,
} as any)
const NationsSlugRoute = NationsSlugRouteImport.update({
  id: '/$slug',
  path: '/$slug',
  getParentRoute: () => NationsRoute,
} as any)
const PartsIndexRoute = PartsIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => PartsRoute,
} as any)
const PartsIdRoute = PartsIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => PartsRoute,
} as any)
const YardsIdRoute = YardsIdRouteImport.update({
  id: '/yards/$id',
  path: '/yards/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAuthSplatRoute = ApiAuthSplatRouteImport.update({
  id: '/api/auth/$',
  path: '/api/auth/$',
  getParentRoute: () => rootRouteImport,
} as any)
const NationsSlugIndexRoute = NationsSlugIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => NationsSlugRoute,
} as any)
const NationsSlugThreadIdRoute = NationsSlugThreadIdRouteImport.update({
  id: '/$threadId',
  path: '/$threadId',
  getParentRoute: () => NationsSlugRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/cars': typeof CarsRouteWithChildren
  '/compare': typeof CompareRoute
  '/desk': typeof DeskRoute
  '/garage': typeof GarageRoute
  '/how-it-works': typeof HowItWorksRoute
  '/insights': typeof InsightsRoute
  '/login': typeof LoginRoute
  '/nations': typeof NationsRouteWithChildren
  '/notification': typeof NotificationRoute
  '/notifications': typeof NotificationsRoute
  '/parts': typeof PartsRouteWithChildren
  '/sell': typeof SellRoute
  '/sign-up': typeof SignUpRoute
  '/cars/$id': typeof CarsIdRoute
  '/listings/$id': typeof ListingsIdRoute
  '/nations/$slug': typeof NationsSlugRouteWithChildren
  '/parts/$id': typeof PartsIdRoute
  '/yards/$id': typeof YardsIdRoute
  '/cars/': typeof CarsIndexRoute
  '/nations/': typeof NationsIndexRoute
  '/parts/': typeof PartsIndexRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/nations/$slug/$threadId': typeof NationsSlugThreadIdRoute
  '/nations/$slug/': typeof NationsSlugIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/compare': typeof CompareRoute
  '/desk': typeof DeskRoute
  '/garage': typeof GarageRoute
  '/how-it-works': typeof HowItWorksRoute
  '/insights': typeof InsightsRoute
  '/login': typeof LoginRoute
  '/notification': typeof NotificationRoute
  '/notifications': typeof NotificationsRoute
  '/sell': typeof SellRoute
  '/sign-up': typeof SignUpRoute
  '/cars/$id': typeof CarsIdRoute
  '/listings/$id': typeof ListingsIdRoute
  '/parts/$id': typeof PartsIdRoute
  '/yards/$id': typeof YardsIdRoute
  '/cars': typeof CarsIndexRoute
  '/nations': typeof NationsIndexRoute
  '/parts': typeof PartsIndexRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/nations/$slug/$threadId': typeof NationsSlugThreadIdRoute
  '/nations/$slug': typeof NationsSlugIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/cars': typeof CarsRouteWithChildren
  '/compare': typeof CompareRoute
  '/desk': typeof DeskRoute
  '/garage': typeof GarageRoute
  '/how-it-works': typeof HowItWorksRoute
  '/insights': typeof InsightsRoute
  '/login': typeof LoginRoute
  '/nations': typeof NationsRouteWithChildren
  '/notification': typeof NotificationRoute
  '/notifications': typeof NotificationsRoute
  '/parts': typeof PartsRouteWithChildren
  '/sell': typeof SellRoute
  '/sign-up': typeof SignUpRoute
  '/cars/$id': typeof CarsIdRoute
  '/listings/$id': typeof ListingsIdRoute
  '/nations/$slug': typeof NationsSlugRouteWithChildren
  '/parts/$id': typeof PartsIdRoute
  '/yards/$id': typeof YardsIdRoute
  '/cars/': typeof CarsIndexRoute
  '/nations/': typeof NationsIndexRoute
  '/parts/': typeof PartsIndexRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/nations/$slug/$threadId': typeof NationsSlugThreadIdRoute
  '/nations/$slug/': typeof NationsSlugIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/cars'
    | '/compare'
    | '/desk'
    | '/garage'
    | '/how-it-works'
    | '/insights'
    | '/login'
    | '/nations'
    | '/notification'
    | '/notifications'
    | '/parts'
    | '/sell'
    | '/sign-up'
    | '/cars/$id'
    | '/listings/$id'
    | '/nations/$slug'
    | '/parts/$id'
    | '/yards/$id'
    | '/cars/'
    | '/nations/'
    | '/parts/'
    | '/api/auth/$'
    | '/nations/$slug/$threadId'
    | '/nations/$slug/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/compare'
    | '/desk'
    | '/garage'
    | '/how-it-works'
    | '/insights'
    | '/login'
    | '/notification'
    | '/notifications'
    | '/sell'
    | '/sign-up'
    | '/cars/$id'
    | '/listings/$id'
    | '/parts/$id'
    | '/yards/$id'
    | '/cars'
    | '/nations'
    | '/parts'
    | '/api/auth/$'
    | '/nations/$slug/$threadId'
    | '/nations/$slug'
  id:
    | '__root__'
    | '/'
    | '/cars'
    | '/compare'
    | '/desk'
    | '/garage'
    | '/how-it-works'
    | '/insights'
    | '/login'
    | '/nations'
    | '/notification'
    | '/notifications'
    | '/parts'
    | '/sell'
    | '/sign-up'
    | '/cars/$id'
    | '/listings/$id'
    | '/nations/$slug'
    | '/parts/$id'
    | '/yards/$id'
    | '/cars/'
    | '/nations/'
    | '/parts/'
    | '/api/auth/$'
    | '/nations/$slug/$threadId'
    | '/nations/$slug/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  CarsRoute: typeof CarsRouteWithChildren
  CompareRoute: typeof CompareRoute
  DeskRoute: typeof DeskRoute
  GarageRoute: typeof GarageRoute
  HowItWorksRoute: typeof HowItWorksRoute
  InsightsRoute: typeof InsightsRoute
  LoginRoute: typeof LoginRoute
  NationsRoute: typeof NationsRouteWithChildren
  NotificationRoute: typeof NotificationRoute
  NotificationsRoute: typeof NotificationsRoute
  PartsRoute: typeof PartsRouteWithChildren
  SellRoute: typeof SellRoute
  SignUpRoute: typeof SignUpRoute
  ListingsIdRoute: typeof ListingsIdRoute
  YardsIdRoute: typeof YardsIdRoute
  ApiAuthSplatRoute: typeof ApiAuthSplatRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cars': {
      id: '/cars'
      path: '/cars'
      fullPath: '/cars'
      preLoaderRoute: typeof CarsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/compare': {
      id: '/compare'
      path: '/compare'
      fullPath: '/compare'
      preLoaderRoute: typeof CompareRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/desk': {
      id: '/desk'
      path: '/desk'
      fullPath: '/desk'
      preLoaderRoute: typeof DeskRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/garage': {
      id: '/garage'
      path: '/garage'
      fullPath: '/garage'
      preLoaderRoute: typeof GarageRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/how-it-works': {
      id: '/how-it-works'
      path: '/how-it-works'
      fullPath: '/how-it-works'
      preLoaderRoute: typeof HowItWorksRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/insights': {
      id: '/insights'
      path: '/insights'
      fullPath: '/insights'
      preLoaderRoute: typeof InsightsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/nations': {
      id: '/nations'
      path: '/nations'
      fullPath: '/nations'
      preLoaderRoute: typeof NationsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/notification': {
      id: '/notification'
      path: '/notification'
      fullPath: '/notification'
      preLoaderRoute: typeof NotificationRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/notifications': {
      id: '/notifications'
      path: '/notifications'
      fullPath: '/notifications'
      preLoaderRoute: typeof NotificationsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/parts': {
      id: '/parts'
      path: '/parts'
      fullPath: '/parts'
      preLoaderRoute: typeof PartsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sell': {
      id: '/sell'
      path: '/sell'
      fullPath: '/sell'
      preLoaderRoute: typeof SellRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sign-up': {
      id: '/sign-up'
      path: '/sign-up'
      fullPath: '/sign-up'
      preLoaderRoute: typeof SignUpRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cars/': {
      id: '/cars/'
      path: '/'
      fullPath: '/cars/'
      preLoaderRoute: typeof CarsIndexRouteImport
      parentRoute: typeof CarsRoute
    }
    '/cars/$id': {
      id: '/cars/$id'
      path: '/$id'
      fullPath: '/cars/$id'
      preLoaderRoute: typeof CarsIdRouteImport
      parentRoute: typeof CarsRoute
    }
    '/listings/$id': {
      id: '/listings/$id'
      path: '/listings/$id'
      fullPath: '/listings/$id'
      preLoaderRoute: typeof ListingsIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/nations/': {
      id: '/nations/'
      path: '/'
      fullPath: '/nations/'
      preLoaderRoute: typeof NationsIndexRouteImport
      parentRoute: typeof NationsRoute
    }
    '/nations/$slug': {
      id: '/nations/$slug'
      path: '/$slug'
      fullPath: '/nations/$slug'
      preLoaderRoute: typeof NationsSlugRouteImport
      parentRoute: typeof NationsRoute
    }
    '/parts/': {
      id: '/parts/'
      path: '/'
      fullPath: '/parts/'
      preLoaderRoute: typeof PartsIndexRouteImport
      parentRoute: typeof PartsRoute
    }
    '/parts/$id': {
      id: '/parts/$id'
      path: '/$id'
      fullPath: '/parts/$id'
      preLoaderRoute: typeof PartsIdRouteImport
      parentRoute: typeof PartsRoute
    }
    '/yards/$id': {
      id: '/yards/$id'
      path: '/yards/$id'
      fullPath: '/yards/$id'
      preLoaderRoute: typeof YardsIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/auth/$': {
      id: '/api/auth/$'
      path: '/api/auth/$'
      fullPath: '/api/auth/$'
      preLoaderRoute: typeof ApiAuthSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/nations/$slug/': {
      id: '/nations/$slug/'
      path: '/'
      fullPath: '/nations/$slug/'
      preLoaderRoute: typeof NationsSlugIndexRouteImport
      parentRoute: typeof NationsSlugRoute
    }
    '/nations/$slug/$threadId': {
      id: '/nations/$slug/$threadId'
      path: '/$threadId'
      fullPath: '/nations/$slug/$threadId'
      preLoaderRoute: typeof NationsSlugThreadIdRouteImport
      parentRoute: typeof NationsSlugRoute
    }
  }
}

interface CarsRouteChildren {
  CarsIdRoute: typeof CarsIdRoute
  CarsIndexRoute: typeof CarsIndexRoute
}

const CarsRouteChildren: CarsRouteChildren = {
  CarsIdRoute: CarsIdRoute,
  CarsIndexRoute: CarsIndexRoute,
}

const CarsRouteWithChildren = CarsRoute._addFileChildren(CarsRouteChildren)

interface NationsSlugRouteChildren {
  NationsSlugThreadIdRoute: typeof NationsSlugThreadIdRoute
  NationsSlugIndexRoute: typeof NationsSlugIndexRoute
}

const NationsSlugRouteChildren: NationsSlugRouteChildren = {
  NationsSlugThreadIdRoute: NationsSlugThreadIdRoute,
  NationsSlugIndexRoute: NationsSlugIndexRoute,
}

const NationsSlugRouteWithChildren = NationsSlugRoute._addFileChildren(
  NationsSlugRouteChildren,
)

interface NationsRouteChildren {
  NationsSlugRoute: typeof NationsSlugRouteWithChildren
  NationsIndexRoute: typeof NationsIndexRoute
}

const NationsRouteChildren: NationsRouteChildren = {
  NationsSlugRoute: NationsSlugRouteWithChildren,
  NationsIndexRoute: NationsIndexRoute,
}

const NationsRouteWithChildren =
  NationsRoute._addFileChildren(NationsRouteChildren)

interface PartsRouteChildren {
  PartsIdRoute: typeof PartsIdRoute
  PartsIndexRoute: typeof PartsIndexRoute
}

const PartsRouteChildren: PartsRouteChildren = {
  PartsIdRoute: PartsIdRoute,
  PartsIndexRoute: PartsIndexRoute,
}

const PartsRouteWithChildren = PartsRoute._addFileChildren(PartsRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  CarsRoute: CarsRouteWithChildren,
  CompareRoute: CompareRoute,
  DeskRoute: DeskRoute,
  GarageRoute: GarageRoute,
  HowItWorksRoute: HowItWorksRoute,
  InsightsRoute: InsightsRoute,
  LoginRoute: LoginRoute,
  NationsRoute: NationsRouteWithChildren,
  NotificationRoute: NotificationRoute,
  NotificationsRoute: NotificationsRoute,
  PartsRoute: PartsRouteWithChildren,
  SellRoute: SellRoute,
  SignUpRoute: SignUpRoute,
  ListingsIdRoute: ListingsIdRoute,
  YardsIdRoute: YardsIdRoute,
  ApiAuthSplatRoute: ApiAuthSplatRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
