/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AccountRouteImport } from './routes/account'
import { Route as CarsRouteImport } from './routes/cars'
import { Route as CompareRouteImport } from './routes/compare'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as CreateClubRouteImport } from './routes/create-club'
import { Route as DeskRouteImport } from './routes/desk'
import { Route as GarageRouteImport } from './routes/garage'
import { Route as HowItWorksRouteImport } from './routes/how-it-works'
import { Route as InsightsRouteImport } from './routes/insights'
import { Route as LoginRouteImport } from './routes/login'
import { Route as NationsRouteImport } from './routes/nations'
import { Route as NotificationRouteImport } from './routes/notification'
import { Route as NotificationsRouteImport } from './routes/notifications'
import { Route as PartsRouteImport } from './routes/parts'
import { Route as SellRouteImport } from './routes/sell'
import { Route as SignUpRouteImport } from './routes/sign-up'
import { Route as AccountIndexRouteImport } from './routes/account.index'
import { Route as AccountUpgradeRouteImport } from './routes/account.upgrade'
import { Route as ApiUploadRouteImport } from './routes/api/upload'
import { Route as CarsIndexRouteImport } from './routes/cars.index'
import { Route as CarsIdRouteImport } from './routes/cars.$id'
import { Route as GarageIndexRouteImport } from './routes/garage.index'
import { Route as GarageIdRouteImport } from './routes/garage.$id'
import { Route as ListingsIdRouteImport } from './routes/listings.$id'
import { Route as NationsIndexRouteImport } from './routes/nations.index'
import { Route as NationsSlugRouteImport } from './routes/nations.$slug'
import { Route as PartsIndexRouteImport } from './routes/parts.index'
import { Route as PartsIdRouteImport } from './routes/parts.$id'
import { Route as YardsSlugRouteImport } from './routes/yards.$slug'
import { Route as ApiAuthSplatRouteImport } from './routes/api/auth/$'
import { Route as NationsSlugIndexRouteImport } from './routes/nations.$slug.index'
import { Route as NationsSlugThreadIdRouteImport } from './routes/nations.$slug.$threadId'
import { Route as NationsSlugManageRouteImport } from './routes/nations.$slug.manage'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AccountRoute = AccountRouteImport.update({
  id: '/account',
  path: '/account',
  getParentRoute: () => rootRouteImport,
} as any)
const CarsRoute = CarsRouteImport.update({
  id: '/cars',
  path: '/cars',
  getParentRoute: () => rootRouteImport,
} as any)
const CompareRoute = CompareRouteImport.update({
  id: '/compare',
  path: '/compare',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const CreateClubRoute = CreateClubRouteImport.update({
  id: '/create-club',
  path: '/create-club',
  getParentRoute: () => rootRouteImport,
} as any)
const DeskRoute = DeskRouteImport.update({
  id: '/desk',
  path: '/desk',
  getParentRoute: () => rootRouteImport,
} as any)
const GarageRoute = GarageRouteImport.update({
  id: '/garage',
  path: '/garage',
  getParentRoute: () => rootRouteImport,
} as any)
const HowItWorksRoute = HowItWorksRouteImport.update({
  id: '/how-it-works',
  path: '/how-it-works',
  getParentRoute: () => rootRouteImport,
} as any)
const InsightsRoute = InsightsRouteImport.update({
  id: '/insights',
  path: '/insights',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const NationsRoute = NationsRouteImport.update({
  id: '/nations',
  path: '/nations',
  getParentRoute: () => rootRouteImport,
} as any)
const NotificationRoute = NotificationRouteImport.update({
  id: '/notification',
  path: '/notification',
  getParentRoute: () => rootRouteImport,
} as any)
const NotificationsRoute = NotificationsRouteImport.update({
  id: '/notifications',
  path: '/notifications',
  getParentRoute: () => rootRouteImport,
} as any)
const PartsRoute = PartsRouteImport.update({
  id: '/parts',
  path: '/parts',
  getParentRoute: () => rootRouteImport,
} as any)
const SellRoute = SellRouteImport.update({
  id: '/sell',
  path: '/sell',
  getParentRoute: () => rootRouteImport,
} as any)
const SignUpRoute = SignUpRouteImport.update({
  id: '/sign-up',
  path: '/sign-up',
  getParentRoute: () => rootRouteImport,
} as any)
const AccountIndexRoute = AccountIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AccountRoute,
} as any)
const AccountUpgradeRoute = AccountUpgradeRouteImport.update({
  id: '/upgrade',
  path: '/upgrade',
  getParentRoute: () => AccountRoute,
} as any)
const ApiUploadRoute = ApiUploadRouteImport.update({
  id: '/api/upload',
  path: '/api/upload',
  getParentRoute: () => rootRouteImport,
} as any)
const CarsIndexRoute = CarsIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => CarsRoute,
} as any)
const CarsIdRoute = CarsIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => CarsRoute,
} as any)
const GarageIndexRoute = GarageIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => GarageRoute,
} as any)
const GarageIdRoute = GarageIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => GarageRoute,
} as any)
const ListingsIdRoute = ListingsIdRouteImport.update({
  id: '/listings/$id',
  path: '/listings/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const NationsIndexRoute = NationsIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => NationsRoute,
} as any)
const NationsSlugRoute = NationsSlugRouteImport.update({
  id: '/$slug',
  path: '/$slug',
  getParentRoute: () => NationsRoute,
} as any)
const PartsIndexRoute = PartsIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => PartsRoute,
} as any)
const PartsIdRoute = PartsIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => PartsRoute,
} as any)
const YardsSlugRoute = YardsSlugRouteImport.update({
  id: '/yards/$slug',
  path: '/yards/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAuthSplatRoute = ApiAuthSplatRouteImport.update({
  id: '/api/auth/$',
  path: '/api/auth/$',
  getParentRoute: () => rootRouteImport,
} as any)
const NationsSlugIndexRoute = NationsSlugIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => NationsSlugRoute,
} as any)
const NationsSlugThreadIdRoute = NationsSlugThreadIdRouteImport.update({
  id: '/$threadId',
  path: '/$threadId',
  getParentRoute: () => NationsSlugRoute,
} as any)
const NationsSlugManageRoute = NationsSlugManageRouteImport.update({
  id: '/manage',
  path: '/manage',
  getParentRoute: () => NationsSlugRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/account': typeof AccountRouteWithChildren
  '/cars': typeof CarsRouteWithChildren
  '/compare': typeof CompareRoute
  '/contact': typeof ContactRoute
  '/create-club': typeof CreateClubRoute
  '/desk': typeof DeskRoute
  '/garage': typeof GarageRouteWithChildren
  '/how-it-works': typeof HowItWorksRoute
  '/insights': typeof InsightsRoute
  '/login': typeof LoginRoute
  '/nations': typeof NationsRouteWithChildren
  '/notification': typeof NotificationRoute
  '/notifications': typeof NotificationsRoute
  '/parts': typeof PartsRouteWithChildren
  '/sell': typeof SellRoute
  '/sign-up': typeof SignUpRoute
  '/account/upgrade': typeof AccountUpgradeRoute
  '/api/upload': typeof ApiUploadRoute
  '/cars/$id': typeof CarsIdRoute
  '/garage/$id': typeof GarageIdRoute
  '/listings/$id': typeof ListingsIdRoute
  '/nations/$slug': typeof NationsSlugRouteWithChildren
  '/parts/$id': typeof PartsIdRoute
  '/yards/$slug': typeof YardsSlugRoute
  '/account/': typeof AccountIndexRoute
  '/cars/': typeof CarsIndexRoute
  '/garage/': typeof GarageIndexRoute
  '/nations/': typeof NationsIndexRoute
  '/parts/': typeof PartsIndexRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/nations/$slug/$threadId': typeof NationsSlugThreadIdRoute
  '/nations/$slug/manage': typeof NationsSlugManageRoute
  '/nations/$slug/': typeof NationsSlugIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/compare': typeof CompareRoute
  '/contact': typeof ContactRoute
  '/create-club': typeof CreateClubRoute
  '/desk': typeof DeskRoute
  '/how-it-works': typeof HowItWorksRoute
  '/insights': typeof InsightsRoute
  '/login': typeof LoginRoute
  '/notification': typeof NotificationRoute
  '/notifications': typeof NotificationsRoute
  '/sell': typeof SellRoute
  '/sign-up': typeof SignUpRoute
  '/account/upgrade': typeof AccountUpgradeRoute
  '/api/upload': typeof ApiUploadRoute
  '/cars/$id': typeof CarsIdRoute
  '/garage/$id': typeof GarageIdRoute
  '/listings/$id': typeof ListingsIdRoute
  '/parts/$id': typeof PartsIdRoute
  '/yards/$slug': typeof YardsSlugRoute
  '/account': typeof AccountIndexRoute
  '/cars': typeof CarsIndexRoute
  '/garage': typeof GarageIndexRoute
  '/nations': typeof NationsIndexRoute
  '/parts': typeof PartsIndexRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/nations/$slug/$threadId': typeof NationsSlugThreadIdRoute
  '/nations/$slug/manage': typeof NationsSlugManageRoute
  '/nations/$slug': typeof NationsSlugIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/account': typeof AccountRouteWithChildren
  '/cars': typeof CarsRouteWithChildren
  '/compare': typeof CompareRoute
  '/contact': typeof ContactRoute
  '/create-club': typeof CreateClubRoute
  '/desk': typeof DeskRoute
  '/garage': typeof GarageRouteWithChildren
  '/how-it-works': typeof HowItWorksRoute
  '/insights': typeof InsightsRoute
  '/login': typeof LoginRoute
  '/nations': typeof NationsRouteWithChildren
  '/notification': typeof NotificationRoute
  '/notifications': typeof NotificationsRoute
  '/parts': typeof PartsRouteWithChildren
  '/sell': typeof SellRoute
  '/sign-up': typeof SignUpRoute
  '/account/upgrade': typeof AccountUpgradeRoute
  '/api/upload': typeof ApiUploadRoute
  '/cars/$id': typeof CarsIdRoute
  '/garage/$id': typeof GarageIdRoute
  '/listings/$id': typeof ListingsIdRoute
  '/nations/$slug': typeof NationsSlugRouteWithChildren
  '/parts/$id': typeof PartsIdRoute
  '/yards/$slug': typeof YardsSlugRoute
  '/account/': typeof AccountIndexRoute
  '/cars/': typeof CarsIndexRoute
  '/garage/': typeof GarageIndexRoute
  '/nations/': typeof NationsIndexRoute
  '/parts/': typeof PartsIndexRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/nations/$slug/$threadId': typeof NationsSlugThreadIdRoute
  '/nations/$slug/manage': typeof NationsSlugManageRoute
  '/nations/$slug/': typeof NationsSlugIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/account'
    | '/cars'
    | '/compare'
    | '/contact'
    | '/create-club'
    | '/desk'
    | '/garage'
    | '/how-it-works'
    | '/insights'
    | '/login'
    | '/nations'
    | '/notification'
    | '/notifications'
    | '/parts'
    | '/sell'
    | '/sign-up'
    | '/account/upgrade'
    | '/api/upload'
    | '/cars/$id'
    | '/garage/$id'
    | '/listings/$id'
    | '/nations/$slug'
    | '/parts/$id'
    | '/yards/$slug'
    | '/account/'
    | '/cars/'
    | '/garage/'
    | '/nations/'
    | '/parts/'
    | '/api/auth/$'
    | '/nations/$slug/$threadId'
    | '/nations/$slug/manage'
    | '/nations/$slug/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/compare'
    | '/contact'
    | '/create-club'
    | '/desk'
    | '/how-it-works'
    | '/insights'
    | '/login'
    | '/notification'
    | '/notifications'
    | '/sell'
    | '/sign-up'
    | '/account/upgrade'
    | '/api/upload'
    | '/cars/$id'
    | '/garage/$id'
    | '/listings/$id'
    | '/parts/$id'
    | '/yards/$slug'
    | '/account'
    | '/cars'
    | '/garage'
    | '/nations'
    | '/parts'
    | '/api/auth/$'
    | '/nations/$slug/$threadId'
    | '/nations/$slug/manage'
    | '/nations/$slug'
  id:
    | '__root__'
    | '/'
    | '/account'
    | '/cars'
    | '/compare'
    | '/contact'
    | '/create-club'
    | '/desk'
    | '/garage'
    | '/how-it-works'
    | '/insights'
    | '/login'
    | '/nations'
    | '/notification'
    | '/notifications'
    | '/parts'
    | '/sell'
    | '/sign-up'
    | '/account/upgrade'
    | '/api/upload'
    | '/cars/$id'
    | '/garage/$id'
    | '/listings/$id'
    | '/nations/$slug'
    | '/parts/$id'
    | '/yards/$slug'
    | '/account/'
    | '/cars/'
    | '/garage/'
    | '/nations/'
    | '/parts/'
    | '/api/auth/$'
    | '/nations/$slug/$threadId'
    | '/nations/$slug/manage'
    | '/nations/$slug/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AccountRoute: typeof AccountRouteWithChildren
  CarsRoute: typeof CarsRouteWithChildren
  CompareRoute: typeof CompareRoute
  ContactRoute: typeof ContactRoute
  CreateClubRoute: typeof CreateClubRoute
  DeskRoute: typeof DeskRoute
  GarageRoute: typeof GarageRouteWithChildren
  HowItWorksRoute: typeof HowItWorksRoute
  InsightsRoute: typeof InsightsRoute
  LoginRoute: typeof LoginRoute
  NationsRoute: typeof NationsRouteWithChildren
  NotificationRoute: typeof NotificationRoute
  NotificationsRoute: typeof NotificationsRoute
  PartsRoute: typeof PartsRouteWithChildren
  SellRoute: typeof SellRoute
  SignUpRoute: typeof SignUpRoute
  ApiUploadRoute: typeof ApiUploadRoute
  ListingsIdRoute: typeof ListingsIdRoute
  YardsSlugRoute: typeof YardsSlugRoute
  ApiAuthSplatRoute: typeof ApiAuthSplatRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/account': {
      id: '/account'
      path: '/account'
      fullPath: '/account'
      preLoaderRoute: typeof AccountRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cars': {
      id: '/cars'
      path: '/cars'
      fullPath: '/cars'
      preLoaderRoute: typeof CarsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/compare': {
      id: '/compare'
      path: '/compare'
      fullPath: '/compare'
      preLoaderRoute: typeof CompareRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/create-club': {
      id: '/create-club'
      path: '/create-club'
      fullPath: '/create-club'
      preLoaderRoute: typeof CreateClubRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/desk': {
      id: '/desk'
      path: '/desk'
      fullPath: '/desk'
      preLoaderRoute: typeof DeskRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/garage': {
      id: '/garage'
      path: '/garage'
      fullPath: '/garage'
      preLoaderRoute: typeof GarageRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/how-it-works': {
      id: '/how-it-works'
      path: '/how-it-works'
      fullPath: '/how-it-works'
      preLoaderRoute: typeof HowItWorksRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/insights': {
      id: '/insights'
      path: '/insights'
      fullPath: '/insights'
      preLoaderRoute: typeof InsightsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/nations': {
      id: '/nations'
      path: '/nations'
      fullPath: '/nations'
      preLoaderRoute: typeof NationsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/notification': {
      id: '/notification'
      path: '/notification'
      fullPath: '/notification'
      preLoaderRoute: typeof NotificationRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/notifications': {
      id: '/notifications'
      path: '/notifications'
      fullPath: '/notifications'
      preLoaderRoute: typeof NotificationsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/parts': {
      id: '/parts'
      path: '/parts'
      fullPath: '/parts'
      preLoaderRoute: typeof PartsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sell': {
      id: '/sell'
      path: '/sell'
      fullPath: '/sell'
      preLoaderRoute: typeof SellRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sign-up': {
      id: '/sign-up'
      path: '/sign-up'
      fullPath: '/sign-up'
      preLoaderRoute: typeof SignUpRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/account/': {
      id: '/account/'
      path: '/'
      fullPath: '/account/'
      preLoaderRoute: typeof AccountIndexRouteImport
      parentRoute: typeof AccountRoute
    }
    '/account/upgrade': {
      id: '/account/upgrade'
      path: '/upgrade'
      fullPath: '/account/upgrade'
      preLoaderRoute: typeof AccountUpgradeRouteImport
      parentRoute: typeof AccountRoute
    }
    '/api/upload': {
      id: '/api/upload'
      path: '/api/upload'
      fullPath: '/api/upload'
      preLoaderRoute: typeof ApiUploadRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cars/': {
      id: '/cars/'
      path: '/'
      fullPath: '/cars/'
      preLoaderRoute: typeof CarsIndexRouteImport
      parentRoute: typeof CarsRoute
    }
    '/cars/$id': {
      id: '/cars/$id'
      path: '/$id'
      fullPath: '/cars/$id'
      preLoaderRoute: typeof CarsIdRouteImport
      parentRoute: typeof CarsRoute
    }
    '/garage/': {
      id: '/garage/'
      path: '/'
      fullPath: '/garage/'
      preLoaderRoute: typeof GarageIndexRouteImport
      parentRoute: typeof GarageRoute
    }
    '/garage/$id': {
      id: '/garage/$id'
      path: '/$id'
      fullPath: '/garage/$id'
      preLoaderRoute: typeof GarageIdRouteImport
      parentRoute: typeof GarageRoute
    }
    '/listings/$id': {
      id: '/listings/$id'
      path: '/listings/$id'
      fullPath: '/listings/$id'
      preLoaderRoute: typeof ListingsIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/nations/': {
      id: '/nations/'
      path: '/'
      fullPath: '/nations/'
      preLoaderRoute: typeof NationsIndexRouteImport
      parentRoute: typeof NationsRoute
    }
    '/nations/$slug': {
      id: '/nations/$slug'
      path: '/$slug'
      fullPath: '/nations/$slug'
      preLoaderRoute: typeof NationsSlugRouteImport
      parentRoute: typeof NationsRoute
    }
    '/parts/': {
      id: '/parts/'
      path: '/'
      fullPath: '/parts/'
      preLoaderRoute: typeof PartsIndexRouteImport
      parentRoute: typeof PartsRoute
    }
    '/parts/$id': {
      id: '/parts/$id'
      path: '/$id'
      fullPath: '/parts/$id'
      preLoaderRoute: typeof PartsIdRouteImport
      parentRoute: typeof PartsRoute
    }
    '/yards/$slug': {
      id: '/yards/$slug'
      path: '/yards/$slug'
      fullPath: '/yards/$slug'
      preLoaderRoute: typeof YardsSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/auth/$': {
      id: '/api/auth/$'
      path: '/api/auth/$'
      fullPath: '/api/auth/$'
      preLoaderRoute: typeof ApiAuthSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/nations/$slug/': {
      id: '/nations/$slug/'
      path: '/'
      fullPath: '/nations/$slug/'
      preLoaderRoute: typeof NationsSlugIndexRouteImport
      parentRoute: typeof NationsSlugRoute
    }
    '/nations/$slug/$threadId': {
      id: '/nations/$slug/$threadId'
      path: '/$threadId'
      fullPath: '/nations/$slug/$threadId'
      preLoaderRoute: typeof NationsSlugThreadIdRouteImport
      parentRoute: typeof NationsSlugRoute
    }
    '/nations/$slug/manage': {
      id: '/nations/$slug/manage'
      path: '/manage'
      fullPath: '/nations/$slug/manage'
      preLoaderRoute: typeof NationsSlugManageRouteImport
      parentRoute: typeof NationsSlugRoute
    }
  }
}

interface AccountRouteChildren {
  AccountUpgradeRoute: typeof AccountUpgradeRoute
  AccountIndexRoute: typeof AccountIndexRoute
}

const AccountRouteChildren: AccountRouteChildren = {
  AccountUpgradeRoute: AccountUpgradeRoute,
  AccountIndexRoute: AccountIndexRoute,
}

const AccountRouteWithChildren =
  AccountRoute._addFileChildren(AccountRouteChildren)

interface CarsRouteChildren {
  CarsIdRoute: typeof CarsIdRoute
  CarsIndexRoute: typeof CarsIndexRoute
}

const CarsRouteChildren: CarsRouteChildren = {
  CarsIdRoute: CarsIdRoute,
  CarsIndexRoute: CarsIndexRoute,
}

const CarsRouteWithChildren = CarsRoute._addFileChildren(CarsRouteChildren)

interface GarageRouteChildren {
  GarageIdRoute: typeof GarageIdRoute
  GarageIndexRoute: typeof GarageIndexRoute
}

const GarageRouteChildren: GarageRouteChildren = {
  GarageIdRoute: GarageIdRoute,
  GarageIndexRoute: GarageIndexRoute,
}

const GarageRouteWithChildren =
  GarageRoute._addFileChildren(GarageRouteChildren)

interface NationsSlugRouteChildren {
  NationsSlugThreadIdRoute: typeof NationsSlugThreadIdRoute
  NationsSlugManageRoute: typeof NationsSlugManageRoute
  NationsSlugIndexRoute: typeof NationsSlugIndexRoute
}

const NationsSlugRouteChildren: NationsSlugRouteChildren = {
  NationsSlugThreadIdRoute: NationsSlugThreadIdRoute,
  NationsSlugManageRoute: NationsSlugManageRoute,
  NationsSlugIndexRoute: NationsSlugIndexRoute,
}

const NationsSlugRouteWithChildren = NationsSlugRoute._addFileChildren(
  NationsSlugRouteChildren,
)

interface NationsRouteChildren {
  NationsSlugRoute: typeof NationsSlugRouteWithChildren
  NationsIndexRoute: typeof NationsIndexRoute
}

const NationsRouteChildren: NationsRouteChildren = {
  NationsSlugRoute: NationsSlugRouteWithChildren,
  NationsIndexRoute: NationsIndexRoute,
}

const NationsRouteWithChildren =
  NationsRoute._addFileChildren(NationsRouteChildren)

interface PartsRouteChildren {
  PartsIdRoute: typeof PartsIdRoute
  PartsIndexRoute: typeof PartsIndexRoute
}

const PartsRouteChildren: PartsRouteChildren = {
  PartsIdRoute: PartsIdRoute,
  PartsIndexRoute: PartsIndexRoute,
}

const PartsRouteWithChildren = PartsRoute._addFileChildren(PartsRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AccountRoute: AccountRouteWithChildren,
  CarsRoute: CarsRouteWithChildren,
  CompareRoute: CompareRoute,
  ContactRoute: ContactRoute,
  CreateClubRoute: CreateClubRoute,
  DeskRoute: DeskRoute,
  GarageRoute: GarageRouteWithChildren,
  HowItWorksRoute: HowItWorksRoute,
  InsightsRoute: InsightsRoute,
  LoginRoute: LoginRoute,
  NationsRoute: NationsRouteWithChildren,
  NotificationRoute: NotificationRoute,
  NotificationsRoute: NotificationsRoute,
  PartsRoute: PartsRouteWithChildren,
  SellRoute: SellRoute,
  SignUpRoute: SignUpRoute,
  ApiUploadRoute: ApiUploadRoute,
  ListingsIdRoute: ListingsIdRoute,
  YardsSlugRoute: YardsSlugRoute,
  ApiAuthSplatRoute: ApiAuthSplatRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
